// js/supabase-config.js
// Generated by MANNOL Setup Wizard on 2026-08-25T20:42:14.953Z
// Place this file at js/supabase-config.js in your deployment.

export const supabaseConfig = {
  url: "https://ightajxyvifpekuwamjz.supabase.co",
  anonKey: "sb_publishable_F0Y8L3f91V7iFgb7CqeMrQ_i3W9-FFa"
};

export const isSupabaseConfigured = true;
